# Generated by Django 2.2.12 on 2020-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
