# Generated by Django 2.2.12 on 2020-06-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0003_auto_20200623_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetsmodel',
            old_name='id',
            new_name='id_tweet',
        ),
    ]
