# Generated by Django 2.2.12 on 2020-06-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0004_auto_20200624_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetsmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tweetsmodel',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tweetsmodel',
            name='Lokasi',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
