# Generated by Django 2.2.12 on 2020-06-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0005_auto_20200626_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetsmodel',
            old_name='Lokasi',
            new_name='lokasi',
        ),
    ]
