# Generated by Django 2.2.12 on 2020-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0006_auto_20200629_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsmodel',
            name='lokasi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
