# Generated by Django 2.2.12 on 2020-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0007_auto_20200719_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsmodel',
            name='lokasi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
