# Generated by Django 2.2.12 on 2020-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0009_auto_20200719_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsmodel',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tweetsmodel',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
