# Generated by Django 2.2.12 on 2020-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0010_auto_20200804_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='jumlah',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
