# Generated by Django 2.2.12 on 2020-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0012_auto_20201103_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='jumlah',
            field=models.IntegerField(default=0),
        ),
    ]
