# Generated by Django 2.2.12 on 2020-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_tweet', '0013_auto_20201103_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
