# Generated by Django 2.2.12 on 2020-06-23 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsuTweet',
            fields=[
                ('id_ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_buat', models.DateField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
