# Generated by Django 2.2.12 on 2020-06-23 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200623_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isutweet',
            name='id_ref',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
