# Generated by Django 2.2.12 on 2020-12-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200623_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isutweet',
            name='judul',
            field=models.CharField(max_length=15),
        ),
    ]
