# Generated by Django 2.2.12 on 2020-06-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('id_isu', models.CharField(max_length=50, null=True)),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
