# Generated by Django 2.2.12 on 2020-06-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistweet',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
