# Generated by Django 2.2.12 on 2020-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200623_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistweet',
            name='lokasi',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
