# Generated by Django 2.2.12 on 2020-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysistweet_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempatHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(blank=True, max_length=30, null=True)),
                ('prov_jumlah', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='analysistweet',
            name='id_isu',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='analysistweet',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='analysistweet',
            name='lokasi',
            field=models.ManyToManyField(to='analysis.TempatHashtag'),
        ),
    ]
