# Generated by Django 2.2.12 on 2020-07-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200629_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisTweet',
        ),
        migrations.DeleteModel(
            name='TempatHashtag',
        ),
    ]
